spring:
  application:
    name: spring-cloud-consul-provider
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: service-producer
server:
  port: 8502

